### ISSUE TITLE
Beware of rebasing/dropping parent commit of `git subrepo` automated commits

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/ingest#21]
`git subrepo` relies on metadata in the .gitrepo file which includes the hash for the parent commit. 

If this parent commit no longer exists, there can be errors in future `git subrepo pull` updates. 
I ran into the following error when I was trying to update ingest/vendored in pathogen-repo-template
```
$ git subrepo pull ingest/vendored -v -d
>>> git rev-parse --verify HEAD
* Assert that working copy is clean: /Users/jlee2346/Repos/nextstrain/pathogen-repo-template
* Check for worktree with branch subrepo/ingest/vendored
  * Fetch the upstream: https://github.com/nextstrain/ingest (main).
>>> git fetch --no-tags --quiet https://github.com/nextstrain/ingest main
  * Get the upstream subrepo HEAD commit.
>>> git rev-parse FETCH_HEAD^0
  * Create ref 'refs/subrepo/ingest/vendored/fetch'.
>>> git update-ref refs/subrepo/ingest/vendored/fetch 9cfed8b1a93e881d85a71aef46e66730ca660523
* Deleting old 'subrepo/ingest/vendored' branch.
* Remove worktree: 
>>> git branch -D subrepo/ingest/vendored
* Create subrepo branch 'subrepo/ingest/vendored'.
  * Check if the 'subrepo/ingest/vendored' branch already exists.
  * Subrepo parent: 0fb3be579140549bd4ef1b7b3aa22a48593911b4
  * Create new commits with parents into the subrepo fetch
>>> git rev-list --reverse --ancestry-path --topo-order 0fb3be579140549bd4ef1b7b3aa22a48593911b4..HEAD
  * Create branch 'subrepo/ingest/vendored' for this new commit set .
>>> git branch subrepo/ingest/vendored 
git-subrepo: Command failed: 'git branch subrepo/ingest/vendored '.
fatal: not a valid object name: ''
```

The logs show it's referencing the parent commit hash (`0fb3be579140549bd4ef1b7b3aa22a48593911b4`) in the [.gitrepo file](https://github.com/nextstrain/pathogen-repo-template/blob/b3e751581afa9646062744db49f8a11cf68879a7/ingest/vendored/.gitrepo#L10). This commit was one I had made locally before rebasing and pushing the new commits to GitHub. 
The actual parent commit hash should be `b82d26d1252897959b42d5122aff94f20bfa05ed`.

**Comment by joverlee521** [comment]
I manually [updated the commit hash](https://github.com/nextstrain/pathogen-repo-template/commit/143581871f1fdcc3ce0d020e1c3ddddffef2ffa9) and then was able to [successfully run](https://github.com/nextstrain/pathogen-repo-template/commit/143581871f1fdcc3ce0d020e1c3ddddffef2ffa9) the `git subrepo pull ingest/vendored` command.

**Comment by victorlin** [comment]
Sorry if you spent a lot of time looking into this! I realized in https://github.com/nextstrain/rsv/commit/12089ed723dd76f2bf4c60f09b005c27a3f88c0c, probably should have said something about it to the group.

Thanks for following up here!
