### ISSUE TITLE
Update existing pathogen repos to vendor ingest scripts

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/ingest#9]
### Context
Depends on #3 

Once we've decided on how to vendor the centralized ingest scripts, we should update the existing pathogen builds to use the ingest scripts. 

This will probably be better to do as an iterative process that happens in parallel with #1. 

### Description
Repos that should be updated to vendor the ingest scripts:

- [x] https://github.com/nextstrain/monkeypox/pull/164
- [x] https://github.com/nextstrain/ncov-ingest/pull/412
- ~[ ] ncov~ [Skipping since not worth complexity](https://github.com/nextstrain/ingest/issues/9#issuecomment-1684223663) 
- [x] https://github.com/nextstrain/rsv/pull/32
- [x] https://github.com/nextstrain/hepatitisB/pull/5
- [x] https://github.com/nextstrain/forecasts-ncov/pull/60 + https://github.com/nextstrain/forecasts-ncov/pull/62

The following repos have WIP PRs for adding ingest to their workflows that can be updated to vendor the scripts:
- [x] https://github.com/nextstrain/dengue/pull/13
- [x] https://github.com/nextstrain/zika/pull/28

**Comment by victorlin** [comment]
To start things off, I'm going to try this for the monkeypox repo.

**Comment by victorlin** [comment]
Is the ncov repo worth including in this initial effort? It has no use for the ingest-specific scripts, but does use `upload-to-s3`+`sha256sum`.

From 690fa990223b7842aef663830b037f4963dcc65e:

> The copy of this script in ncov² has diverged enough that I think it's not worth it to incorporate changes here.
> ² https://github.com/nextstrain/ncov/blob/ba9953f8a61d239176e960b9b2efb925b5dff84b/scripts/upload-to-s3

I assume ncov should keep using its own copy of `upload-to-s3`. That leaves `sha256sum` as the only script to switch over to. This is what that would look like: https://github.com/nextstrain/ncov/compare/fcd7327d8e1ca86dc58134dc6a448327d1f0abe1...79af5caa12a22f3719eeff37fe8a472f8b799c14

The added subrepo complexity in the ncov repo just for the `sha256sum` script is not worth it to me.

**Comment by joverlee521** [comment]
> The added subrepo complexity in the ncov repo just for the sha256sum script is not worth it to me.

Agreed! We can skip the ncov repo.

**Comment by victorlin** [comment]
Assigning @j23414 for dengue and zika.
